### ISSUE TITLE
Account widget renders empty elements when user isn't logged in

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#10]
The Account widget is currently rendering various empty elements when the user isn't logged in. It shouldn't render anything at all.

**Comment by takempf** [comment]
It doesn't seem to be rendering anything extra here: http://preview.303.sites.storytellerhq.com/fanclubs/sparkartjs

Do you have a URL where I can see this behavior?

**Comment by pushred** [comment]
http://preview.229.sites.storytellerhq.com/home, it's happening because I'm wrapping the contents of my custom template in a `customer` section, but that's still present when logged out, even though all of it's properties are null. I see you're nesting `registered` within that, so will do the same.
