### ISSUE TITLE
Account widget preprocessor isn't executed

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#11]
Specifying a preprocessor for the Account widget like so doesn't seem to work:

``` js
fightclub = new sparkart.Fanclub('d828a4cb-f8a7-4bf5-a5bb-5a9eed9c27cb', {

    api_url: 'https://sparkart-services.herokuapp.com/api/v1/consumer',
    templates: {
        account: $('.account.partial').html()
    },
    preprocessors: {
        account: function( context ){

            alert(context.customer);

            return context;

        }
    }

});
```

**Comment by takempf** [comment]
Could I get more information about this issue, namely:
1. The url this occurs at
2. Whether or not the account endpoint is returning an error or success

Do note that preprocessors are only run if the widget's request is _successful_. Error responses aren't preprocessed.

**Comment by pushred** [comment]
http://preview.229.sites.storytellerhq.com/home

If you peek in the editor, `/Fanclub` is where I have the above code. The alert isn't firing but I'm using that widget on every page. The widget is rendering however into `#masthead > .user > .sparkart.fanclub.account`, with a custom template applied.

Since that template is being populated successfully then the endpoint would seem to be successful. In the console I see a successful request at initialization, another for the widget, and none failed.

**Comment by pushred** [comment]
Getting this error when I try to access the Customer object in the preprocessor's context:

```
Uncaught TypeError: Property 'toJSON' of object function ( context ){

                console.log(context.customer);

                return context;

            } is not a function 3829.js:475
(anonymous function) 3829.js:475
(anonymous function) 3829.js:504
fire 3553.js:974
self.fireWith 3553.js:1082
done 3553.js:7788
callback
```

**Comment by pushred** [comment]
Actually, simply adding `account` to the preprocessors object results in this error, commented out for now on UFC, let me know if you want me to re-enable.
