### ISSUE TITLE
Separate templates from library for better review

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#2]
One thought UX & I had earlier that I wanted to share is it would be nice to make the widget templates available outside of the library in this repo for the purposes of review. The concatenated string versions were just difficult for them to see with the less than ideal indentation, no syntax highlighting, etc. It would also allow them to more easily make changes. A simple Ruby or JS script could be used to build the final file for distribution to sites.

**Comment by takempf** [comment]
I'll look into a build system for this script when time allows

**Comment by takempf** [comment]
Templates are now located in `/src/templates`. In order to build the script, make your changes to the files in `src`, then run the `build.js` script. This will generate the sparkart.js seen in the base directory.
