### ISSUE TITLE
Register widget shouldn't redirect to Register page on success

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#21]
The Register widget currently reloads the registration page after it's successfully submitted. I currently have a check to send users back to the home page after this, but we should just do that by default. We should also offer a redirect parameter however for sites that may have a fan club's "home page" somewhere other than `/`.

**Comment by takempf** [comment]
You can specify the redirect url in one of two ways:

``` html
<div class="sparkart fanclub login" data-redirect="http://www.google.com"></div>
```

or

``` javascript
new sparkart.Fanclub( KEY, {
    redirect: {
        login: '/'
    }
});
```
