### ISSUE TITLE
Customer widget is undocumented

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#30]
The customer widget added in [this commit](https://github.com/SparkartGroupInc/sparkart.js/commit/a34c06396f55f76e10e19d9e656412517ccc2111) is undocumented. When adding this documentation I think we should break out widget documentation into the wiki and expand on each of them a bit more. Available configuration parameters, example uses, even screenshots of live examples would be great to have.

The README offers a good level of detail for our use but I fear that it's too advanced for a typical Sparkart UX developer.

**Comment by takempf** [comment]
Technically documented. https://github.com/SparkartGroupInc/sparkart.js/wiki/Customer-widget

If you want more documentation for widgets, that should probably be a separate issue.
