### ISSUE TITLE
Facebook login undocumented / missing in default Login widget template

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#35]
I'm trying to use the Facebook login functionality but I'm not seeing any documentation on it outside of some references to it's existence. I was expecting to see it in the Login & Register widgets. I'm using 0.1.0.

**Comment by takempf** [comment]
https://github.com/SparkartGroupInc/sparkart.js/blob/master/src/templates/login.hbs#L2

**Comment by pushred** [comment]
This will be moved to the new Login view in sparkart services.
