### ISSUE TITLE
Customers can't login using iOS 6.1

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#37]
Something has changed between iOS 6.0.x and 6.1.x that is causing issues with login. I've confirmed that login works on my own 6.0.1 device and confirmed that an issue exists in 6.1 using the [iOS Simulator](http://developer.apple.com/library/ios/#documentation/IDEs/Conceptual/iOS_Simulator_Guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40012848-CH1-SW1) to try logging in on both UFC Fight Club and Curry Testbed. I'm able to view the console in both environments using the [Safari Developer Tools](http://developer.apple.com/library/safari/#documentation/AppleApplications/Reference/SafariWebContent/DebuggingSafarioniPhoneContent/DebuggingSafarioniPhoneContent.html#//apple_ref/doc/uid/TP40006515). Using this configuration here's what an initialized fanclub object looks like:

``` js
authentications: Array[1]
customer: null
key: "d828a4cb-f8a7-4bf5-a5bb-5a9eed9c27cb"
loaded: true
name: "UFC Fight Club"
parameters: Object
preprocessors: Object
templates: Object
```

It looks like there were some [security updates](http://support.apple.com/kb/HT5642) in 6.1 regarding cross-site communication, perhaps one of these changes is the issue.

Note that UFC is planning on pushing mobile signups at this Saturday's fight and would very much like to see this issue resolved in time. As they paid specifically for this ability in the recent redesign the card has been prioritized accordingly.

**Comment by takempf** [comment]
iOS users need to manually allow third party cookies in order for our login approach to work. We'll likely have to use some sort of trickery to get login to work if we keep it like it is. If we move login/registration into the fanclub app proper, we shouldn't have any problems, however.

**Comment by takempf** [comment]
When I see myself implementing this hack I feel less confident about our product's stability: http://stackoverflow.com/questions/9930671/safari-3rd-party-cookie-iframe-trick-no-longer-working

**Comment by pushred** [comment]
We'll be addressing this with https://trello.com/c/0vFMDqJp.

Will close this issue once that is released.
