### ISSUE TITLE
Customers can't login using IE 10

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#40]
The symptoms here are exactly the same as in #37, the `customer` object remains null after submitting the login form. Reproduced in IE 10 running Windows 7.

**Comment by takempf** [comment]
This is another cookie issue. The updated security settings in IE10 make our approach to sessions very weak. If you want to get it to work, you can go to _Internet Options_ -> _Privacy_ -> _Advanced_ and "always allow session cookies". This might be solved by moving the login page to the fanclub site itself.

**Comment by pushred** [comment]
We'll be addressing this with https://trello.com/c/0vFMDqJp.

Will close this issue once that is released.
