### ISSUE TITLE
Document js.sparkart.net distribution

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#42]

**Comment by takempf** [comment]
I don't really understand this. Is it referring to @shonsherwood 's deployment system?

**Comment by djiang** [comment]
What's the URL for the different versions of sparkart.js?

**Comment by shonsherwood** [comment]
http://js.sparkart.net/sparkart.js/<version>/

sparkart.js and sparkart.min.js are both in that directory.

There is also a current.js and current.min.js in
http://js.sparkart.net/sparkart.js/

On Mon, May 6, 2013 at 4:25 PM, David Jiang notifications@github.comwrote:

> What's the URL for the different versions of sparkart.js?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SparkartGroupInc/sparkart.js/issues/42#issuecomment-17514511
> .

## 

Shon Sherwood
VP Platforms & Services
SPARKART GROUP, INC.
2201 Broadway
Suite 100
Oakland, CA 94612

web:  www.sparkart.com
email:  shon@sparkart.com
phone:  510.420.0201 ext. 333
aim:  shonspark

**Comment by shonsherwood** [comment]
where <version> == git tag, for example 000.001.002

On Mon, May 6, 2013 at 4:29 PM, Shon Sherwood shon@sparkart.com wrote:

> http://js.sparkart.net/sparkart.js/<version>/
> 
> sparkart.js and sparkart.min.js are both in that directory.
> 
> There is also a current.js and current.min.js in
> http://js.sparkart.net/sparkart.js/
> 
> On Mon, May 6, 2013 at 4:25 PM, David Jiang notifications@github.comwrote:
> 
> > What's the URL for the different versions of sparkart.js?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/SparkartGroupInc/sparkart.js/issues/42#issuecomment-17514511
> > .
> 
> ## 
> 
> Shon Sherwood
> VP Platforms & Services
> SPARKART GROUP, INC.
> 2201 Broadway
> Suite 100
> Oakland, CA 94612
> 
> web:  www.sparkart.com
> email:  shon@sparkart.com
> phone:  510.420.0201 ext. 333
> aim:  shonspark

## 

Shon Sherwood
VP Platforms & Services
SPARKART GROUP, INC.
2201 Broadway
Suite 100
Oakland, CA 94612

web:  www.sparkart.com
email:  shon@sparkart.com
phone:  510.420.0201 ext. 333
aim:  shonspark

**Comment by pushred** [comment]
Some documentation was written in the oral tradition here: https://sparkart.campfirenow.com/room/548453/transcript/2013/05/06

I suppose I'll transcribe myself the next time I want this deployed.
