### ISSUE TITLE
Login widget binds submission to all buttons

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#5]
The login widget currently seems to bind login submission to any button element. For example, my widget template features a cancel button. Clicking this submits the form.

**Comment by takempf** [comment]
Login is bound to the `submit` event. The submit event fires when a `<button>` with the type `submit` is clicked, or, in most browsers, if enter is pressed while in certain kinds of input fields. This is most likely a problem with defining button type and not an issue with the login widget itself.

When you make a button inside a form and do not specify a `type`, the button will default to `submit`. If you want to use a button inside of a form for some other reason, you'll need to give the button `type="button"`. In some cases, you might want to use `type="reset"`, if for instance the button is meant to close/clear the form.

**Comment by pushred** [comment]
Ah didn't know that buttons defaulted to `submit`. Thanks
