### ISSUE TITLE
Error in date formatting preventing template rendering in Safari/Firefox

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#50]
There's some sort of issue in the date formatting code that's only happening in Safari and Firefox. It doesn't happen in Chrome or IE 9 & 10. The error returned is:

```
TypeError: DAYS[day_of_week] is undefined
abbr: DAYS[day_of_week].substr( 0, 3 )
```

To reproduce visit http://ufcfightclub.com and select the home page Pre-sales tab. This is a high priority because it's blocking rendering of ticketing links.

**Comment by takempf** [comment]
The problem is here:

``` javascript
var day_of_week = new Date( month +'-'+ day +'-'+ year ).getDay();
```

Looks like some browsers don't parse strings passed to `Date` properly. Luckily, there is a standard method which I was far too silly to utilize the first time around: 

``` javascript
new Date( year, month, day )
```
