### ISSUE TITLE
Login widget often fails to render

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#6]
I'm getting this error frequently when the login widget attempts to render:

```
Uncaught TypeError: Cannot call method 'apply' of undefined
```

Line 681 of sparkart.js

**Comment by takempf** [comment]
This looks like it was a problem with the event triggering system. I'll try to ensure that the event bindings catch and deny anything that isn't a legitimate function.

**Comment by pushred** [comment]
Here was the stacktrace, I'm trying the new version now:

```
Uncaught TypeError: Cannot call method 'apply' of undefined 3829.js:681
Fanclub.trigger 3829.js:681
(anonymous function) 3829.js:295
(anonymous function) 3829.js:472
fire 3553.js:974
self.fireWith 3553.js:1082
done 3553.js:7788
callback
```
