### ISSUE TITLE
Notify Customers about Upgrade/Renewal Policies

### ISSUE THREAD

**Issue by djiang** [sparkartgroup-archive/sparkart.js#63]
Not sure where this should go exactly, but customers should know how upgrades and renewals work:

**Upgrades**
Pay the difference between current plan and new plan to get the new plan benefits right away. The membership end date stays the same.

**Renewals**
If available, a customer can purchase a new membership into the new sales period. The benefits will start right away, but their membership start date gets reset to TODAY instead of being extended by the new plan's duration.

**Comment by djiang** [comment]
In Keith Urban, I just confirmed the following:
- I purchased a Year 1 VIP subscription on 8/25/2013 (expires 8/25/2014 at the earliest)
- New sales period, Year 2 was introduced on 8/29/2013
- I renewed into Year 2 with a Digital subscription today (expires 9/13/2014 at the earliest)
- By doing so, I lost all of my VIP privileges.

**Comment by Timo614** [comment]
We've since introduced new messaging in checkout, closing.
