### ISSUE TITLE
Error thrown in customer preprocessor when user is signed in with expired subscription

### ISSUE THREAD

**Issue by krackydile** [sparkartgroup-archive/sparkart.js#66]
When a user is signed in, the customer preprocessor on line [127](https://github.com/SparkartGroupInc/sparkart.js/blob/master/sparkart.js#L127) is looking for a `start_date` which doesn't exist in the fan club object because the subscription has expired. This error is stopping the customer widget from loading.

This can be seen on [Keith Urban](http://www.keithurban.net) with this account:

adi+apple@sparkart.com / temp123

When the user is logged in, the customer widget should show this in the top right corner:

`Hi, Adapple | Account | Logout`

Can we add a condition to check whether the subscription has expired?

**Comment by pushred** [comment]
@fauntleroy
