### ISSUE TITLE
Password reset functionality shouldn't be in Login widget

### ISSUE THREAD

**Issue by pushred** [sparkartgroup-archive/sparkart.js#8]
The login widget presently includes a password reset form in addition to the login form. Some CSS is required to hide that form. A better implementation would separate the reset functionality from the login widget and allow it to be used independently if desired. The login widget could then render this widget on demand to provide the current functionality without the CSS dependency (and potentially other issues).

**Comment by djiang** [comment]
These functionalities have been moved into the sparkart-services
